version: "2"

services:
    db:
        image: mariadb
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: formation

    php:
        build: ./docker/php-fpm
        links:
            - db
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            APP_ENV: dev
            APP_SECRET: dksqfnvuireojvisdlknbdgsqvdiuoqsijd
            DATABASE_URL: mysql://root:root@db:3306/formation
            MAILER_URL: smtp://mailhog:1025

    nginx:
        image: nginx
        ports:
            - 80
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        working_dir: /var/www/html

    mailhog:
        image: mailhog/mailhog
